name: CI

on:
  push:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

  # Allows A Webhook to be called which will run the Action. Use this for example from WordPress with the GatsbyJS plugin.
  repository_dispatch:
    types: [ publish_blog ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out latest code
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Gatsby Cache Folder
        uses: actions/cache@v3.0.4
        with:
          key: gatsby-cache-folder
          path: .cache

      - name: Gatsby Public Folder
        uses: actions/cache@v3.0.4
        with:
          key: gatsby-public-folder
          path: public

      - name: Yarn cache
        uses: actions/cache@v3.0.4
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn

      - name: Build Gatsby Site
        run: yarn run build    
        
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}          
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./public/"